/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { ExperienceChangeBase } from './ExperienceChangeBase';

/**
 * Describes structure for "defaultCode" type of experience change
 */
export type ExperienceChangeDefaultCodeDataBase = (ExperienceChangeBase & {
    type?: 'defaultCode';
    /**
     * Describes structure for "defaultCode" type of experience change
     */
    data?: {
        /**
         * CSS code to be applied by this change
         */
        css?: string | null;
        /**
         * Javascript code generated by the visual editor or written in the same structure, to be applied by this experience change
         */
        js?: string | null;
        /**
         * Custom javascript code to be applied by this change
         */
        custom_js?: string | null;
    };
});